### PR TITLE
Edit Landing Page CSS

### PR DESCRIPTION
**Pull request by diezcami**
- Added a fixed footer
- Designed the page

### CODE REVIEW

**Comment by swapagarwal** [comment]
Hey! Nice design, but can we use Dropbox logo like that? [Have a look.](https://www.dropbox.com/branding) And instead of "copyright", we can show "made with :heart: by", "designed by", etc. What do you say?

**Comment by diezcami** [comment]
I'm not too sure with the copyright information, I actually just got the dropbox logo from Font Awesome. You could do whatever you want with the footer, though!

**Comment by swapagarwal** [comment]
I think we need to include "Dropbox and the Dropbox logo are trademarks of Dropbox, Inc." in the footer.

**Comment by diezcami** [comment]
Yup, that should work :)
Here's an edited footer snippet, you could change the first line with "Designed by" or whatever you had in mind!
```
<footer class="navbar navbar-fixed-bottom">
	<p align="center" class="text-muted">Made with <i class="fa fa-heart"></i> by 
	<a href="https://github.com/swapagarwal">Swapnil Agarwal</a> <BR />

	Dropbox and the Dropbox logo are trademarks of Dropbox, Inc.
	</p>
</footer>
```

**Comment by swapagarwal** [comment]
Thanks @diezcami :+1: for the awesome design!

**Comment by swapagarwal** [comment]
d5f29fb03b338b83870e9616d9d69ea690b8864d

**Pull request merged**
